In [ ]:
class Pocket:
  def __init__(self, name, cashback):
    self._balance = 0
    self.name = name
    self.cashback = cashback

  def add(self, money):
    self._balance += money

  def cashback_add(self):
    self._balance += self._balance*self.cashback

  @property
  def balance(self):
    return self._balance

In [ ]:
card = Pocket('Avi', 5)
print(card.balance)
card.add(1000)
print(card.balance)

0
1000


In [ ]:
card.cashback_add()
print(card.balance)

6000


In [ ]:
class Card(Pocket):
  def dollar(self):
    return super().balance / 3.4
card1 = Card('Avi', 10)
card1.dollar()
card1.add(1000)
card1.dollar()

294.11764705882354

# ДЗ7

In [1]:
class Money:
    def __init__(self, rubles, kopecks):
        self.rubles = rubles + kopecks // 100
        self.kopecks = kopecks % 100

    def __str__(self):
        return f"{self.rubles},{self.kopecks:02d}"

    def to_kopecks(self):
        return self.rubles * 100 + self.kopecks

    @staticmethod
    def from_kopecks(total_kopecks):
        return Money(total_kopecks // 100, total_kopecks % 100)

    def __add__(self, other):
        return Money.from_kopecks(self.to_kopecks() + other.to_kopecks())

    def __sub__(self, other):
        return Money.from_kopecks(self.to_kopecks() - other.to_kopecks())

    def __truediv__(self, other):
        if isinstance(other, Money):
            return self.to_kopecks() / other.to_kopecks()
        return Money.from_kopecks(int(self.to_kopecks() / other))

    def __mul__(self, factor):
        return Money.from_kopecks(int(self.to_kopecks() * factor))

    def __lt__(self, other):
        return self.to_kopecks() < other.to_kopecks()

    def __le__(self, other):
        return self.to_kopecks() <= other.to_kopecks()

    def __eq__(self, other):
        return self.to_kopecks() == other.to_kopecks()

    def __ne__(self, other):
        return self.to_kopecks() != other.to_kopecks()

    def __gt__(self, other):
        return self.to_kopecks() > other.to_kopecks()

    def __ge__(self, other):
        return self.to_kopecks() >= other.to_kopecks()


m1 = Money(5, 75)  # 5 рублей 75 копеек
m2 = Money(3, 50)  # 3 рубля 50 копеек

print(m1 + m2)
print(m1 - m2)
print(m1 * 2.5)
print(m1 / 2)
print(m1 / m2)
print(m1 > m2)

9,25
2,25
14,37
2,87
1.6428571428571428
True


In [2]:
class Matrix:
    def __init__(self, data):
        self.data = data
        self.rows = len(data)
        self.cols = len(data[0]) if data else 0

    def __str__(self):
        return '\n'.join([' '.join(map(str, row)) for row in self.data])

    def __add__(self, other):
        if self.rows != other.rows or self.cols != other.cols:
            raise ValueError("Матрицы должны быть одного размера")
        return Matrix([[self.data[i][j] + other.data[i][j] for j in range(self.cols)] for i in range(self.rows)])

    def __mul__(self, scalar):
        return Matrix([[self.data[i][j] * scalar for j in range(self.cols)] for i in range(self.rows)])


m1 = Matrix([[1, 2], [3, 4]])
m2 = Matrix([[5, 6], [7, 8]])
print(m1 + m2)
print(m1 * 2)


6 8
10 12
2 4
6 8


In [5]:
import numpy as np

class Structure:
    def __add__(self, other):
        raise NotImplementedError

    def __mul__(self, scalar):
        raise NotImplementedError

class Vector(Structure):
    def __init__(self, data):
        self.data = np.array(data)

    def __str__(self):
        return str(self.data)

    def __add__(self, other):
        if len(self.data) != len(other.data):
            raise ValueError("Векторы должны быть одной длины")
        return Vector(self.data + other.data)

    def __mul__(self, scalar):
        return Vector(self.data * scalar)

class Matrix(Structure):
    def __init__(self, data):
        self.data = np.array(data)

    def __str__(self):
        return str(self.data)

    def __add__(self, other):
        if self.data.shape != other.data.shape:
            raise ValueError("Матрицы должны быть одного размера")
        return Matrix(self.data + other.data)

    def __mul__(self, scalar):
        return Matrix(self.data * scalar)


v1 = Vector([1, 2, 3])
v2 = Vector([4, 5, 6])
print(v1 + v2)
print(v1 * 2)

m1 = Matrix([[1, 2], [3, 4]])
m2 = Matrix([[5, 6], [7, 8]])
print(m1 + m2)
print(m1 * 2)


[5 7 9]
[2 4 6]
[[ 6  8]
 [10 12]]
[[2 4]
 [6 8]]


In [1]:
class Electronics:
    def __init__(self, brand, price):
        self.brand = brand
        self.price = price

    def info(self):
        return f"Бренд: {self.brand}, Цена: {self.price} руб."

class Smartphone(Electronics):
    def __init__(self, brand, price, os, camera_mp):
        super().__init__(brand, price)
        self.os = os
        self.camera_mp = camera_mp

    def info(self):
        return f"{super().info()}, ОС: {self.os}, Камера: {self.camera_mp} МП"

class Laptop(Electronics):
    def __init__(self, brand, price, ram, cpu):
        super().__init__(brand, price)
        self.ram = ram
        self.cpu = cpu

    def info(self):
        return f"{super().info()}, ОЗУ: {self.ram} ГБ, Процессор: {self.cpu}"

class Smartwatch(Electronics):
    def __init__(self, brand, price, battery_life, sport_mode):
        super().__init__(brand, price)
        self.battery_life = battery_life
        self.sport_mode = sport_mode

    def info(self):
        return f"{super().info()}, Время работы: {self.battery_life} ч, Спортивный режим: {'Есть' if self.sport_mode else 'Нет'}"

# Пример использования
smartphone = Smartphone("Apple", 100000, "iOS", 12)
laptop = Laptop("Dell", 80000, 16, "Intel i7")
smartwatch = Smartwatch("Samsung", 20000, 24, True)

print(smartphone.info())
print(laptop.info())
print(smartwatch.info())

Бренд: Apple, Цена: 100000 руб., ОС: iOS, Камера: 12 МП
Бренд: Dell, Цена: 80000 руб., ОЗУ: 16 ГБ, Процессор: Intel i7
Бренд: Samsung, Цена: 20000 руб., Время работы: 24 ч, Спортивный режим: Есть
